In [3]:
import numpy as np
import torch
import torchvision
import pickle
import matplotlib.pyplot as plt

In [4]:
#load the data set
with open('./data/velocity64.pickle', 'rb') as handle:
    velocities = pickle.load(handle)
#normalize the images between -1 and 1
for i in range(velocities.shape[0]):
    velocities[i,:,:,:]=2*(velocities[i,:,:,:]-velocities[i,:,:,:].min())/(velocities[i,:,:,:].max()-velocities[i,:,:,:].min())-1
velocities.shape

(4200, 64, 64, 2)

In [9]:
#load the low resolution set
with open('./Data/velocity8.pickle', 'rb') as handle:
    velocities8 = pickle.load(handle)
#normalize the images between -1 and 1
for i in range(velocities8.shape[0]):
    velocities8[i,:,:,:]=2*(velocities8[i,:,:,:]-velocities8[i,:,:,:].min())/(velocities8[i,:,:,:].max()-velocities8[i,:,:,:].min())-1
velocities8.shape
print(velocities8[0,:,:,0])
sample1 = np.resize(velocities8[0,:,:,:])
print(sample1)

[[-0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752 -0.2837851  -0.27889848 -0.2819069
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752 -0.46114624 -0.5448506  -0.38358516
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752  0.3381344   0.23624766  0.24773574
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752 -0.16897869 -0.52352345 -0.36851436
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752
  -0.27687752 -0.27687752]
 [-0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752 -0.27687752
  -0.27687752 -0.27687752]]
[[-0.27687752 -0.27687752 -0.27687752 -0.27687752]
 [-0.27687752 -0.4535374  -0.27687752  0.56910324]
 [-0.27687752 -0.75356525 -0.27687752 -0.07424957]
 [-0.27687752 -0.27687752 -0.27687752 -

In [9]:
#resize the images of 64 to 8
with open('./data/velocity64.pickle','rb') as small:
    velocities8 = pickle.load(small)
#resize the image
    velocities8 = skimage.transform.resize(velocities8,1.0/8.0)

#normalize the images between -1 and 1
for i in range(velocities8.shape[0]):
    velocities8[i,:,:,:] = 2*(velocities8[i,:,:,:]-velocities8[i,:,:,:].min())/(velocities8[i,:,:,:].max()-velocities8[i,:,:,:].min())-1
velocities8.shape

AttributeError: module 'skimage' has no attribute 'transform'